AllCops:
  TargetRubyVersion: 2.3.1
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'db/seeds.rb'
   - 'db/schema.rb'
   - 'db/migrate/*'
   - 'vendor/bundle/**/*'
   - 'frontend/**/*'
   - 'features/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 150

Style/Documentation:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: mixed
  AllowInnerSlashes: true
